language: go
go:
  - "1.11.x"

sudo: enabled

install: 
  - nvm install node
  - sudo dpkg --add-architecture i386
  - wget -nc https://dl.winehq.org/wine-builds/Release.key
  - sudo apt-key add Release.key
  - sudo apt-add-repository 'deb https://dl.winehq.org/wine-builds/ubuntu/ trusty main'
  - sudo apt-get update
  - sudo apt-get install --install-recommends winehq-stable


script:
  - cd ui && npm run test
  - go build
  - ./gotron
