language: node_js
node_js: 
  - "node"
go:
  - "1.10.x"
install: 
  - npm install
script:
  - npm run build
  - npm run build:react
  - npm run build:typescript
  - npm run build:vue
  - npm run pack:linux
