language: go
go:
  - "1.11.1"

sudo: enabled

install: 
  - nvm install node
  - sudo dpkg --add-architecture i386
  - wget -nc https://dl.winehq.org/wine-builds/Release.key
  - sudo apt-key add Release.key
  - sudo apt-add-repository 'deb https://dl.winehq.org/wine-builds/ubuntu/ trusty main'
  - sudo apt-get update
  - sudo apt-get --allow-unauthenticated install --install-recommends winehq-stable


script:
  - go get -d -v ./...
  - cd example/ui && npm run test
  - cd ../../
  - make test-ci